// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification.proto

package notifications

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Notification struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	TimeStamp            uint64   `protobuf:"varint,4,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{1}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Notification) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Notification) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Notification) GetTimeStamp() uint64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

type NotificationID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationID) Reset()         { *m = NotificationID{} }
func (m *NotificationID) String() string { return proto.CompactTextString(m) }
func (*NotificationID) ProtoMessage()    {}
func (*NotificationID) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{2}
}

func (m *NotificationID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationID.Unmarshal(m, b)
}
func (m *NotificationID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationID.Marshal(b, m, deterministic)
}
func (m *NotificationID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationID.Merge(m, src)
}
func (m *NotificationID) XXX_Size() int {
	return xxx_messageInfo_NotificationID.Size(m)
}
func (m *NotificationID) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationID.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationID proto.InternalMessageInfo

func (m *NotificationID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Notifications struct {
	NotificationList     []*Notification `protobuf:"bytes,1,rep,name=notification_list,json=notificationList,proto3" json:"notification_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Notifications) Reset()         { *m = Notifications{} }
func (m *Notifications) String() string { return proto.CompactTextString(m) }
func (*Notifications) ProtoMessage()    {}
func (*Notifications) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{3}
}

func (m *Notifications) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notifications.Unmarshal(m, b)
}
func (m *Notifications) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notifications.Marshal(b, m, deterministic)
}
func (m *Notifications) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notifications.Merge(m, src)
}
func (m *Notifications) XXX_Size() int {
	return xxx_messageInfo_Notifications.Size(m)
}
func (m *Notifications) XXX_DiscardUnknown() {
	xxx_messageInfo_Notifications.DiscardUnknown(m)
}

var xxx_messageInfo_Notifications proto.InternalMessageInfo

func (m *Notifications) GetNotificationList() []*Notification {
	if m != nil {
		return m.NotificationList
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*Notification)(nil), "Notification")
	proto.RegisterType((*NotificationID)(nil), "NotificationID")
	proto.RegisterType((*Notifications)(nil), "Notifications")
}

func init() { proto.RegisterFile("notification.proto", fileDescriptor_736a457d4a5efa07) }

var fileDescriptor_736a457d4a5efa07 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x87, 0xbb, 0xe9, 0x3f, 0x3a, 0xda, 0xb4, 0xdd, 0x78, 0x58, 0x0a, 0x42, 0xd8, 0x53, 0x4e,
	0x5b, 0x69, 0x6f, 0xde, 0x2a, 0x8a, 0x88, 0xe2, 0x21, 0xbd, 0x79, 0x29, 0x35, 0x59, 0x61, 0x20,
	0x9b, 0x0d, 0xdd, 0xa1, 0xe0, 0x43, 0xf9, 0x8e, 0x92, 0xa8, 0xb0, 0x2b, 0x3d, 0xce, 0x6f, 0xbf,
	0xd9, 0x8f, 0x99, 0x01, 0x5e, 0x5b, 0xc2, 0x0f, 0x2c, 0x0e, 0x84, 0xb6, 0x56, 0xcd, 0xd1, 0x92,
	0x95, 0x63, 0x18, 0x3e, 0x98, 0x86, 0x3e, 0xa5, 0x81, 0xcb, 0x57, 0xef, 0x99, 0xc7, 0x10, 0x61,
	0x29, 0x58, 0xca, 0xb2, 0x49, 0x1e, 0x61, 0xc9, 0xaf, 0x60, 0x48, 0x48, 0x95, 0x16, 0x51, 0x17,
	0xfd, 0x14, 0x5c, 0xc0, 0xb8, 0xb0, 0x35, 0xe9, 0x9a, 0x44, 0xbf, 0xcb, 0xff, 0x4a, 0x7e, 0x0d,
	0x40, 0x68, 0xf4, 0xde, 0xd1, 0xc1, 0x34, 0x62, 0x90, 0xb2, 0x6c, 0x90, 0x4f, 0xda, 0x64, 0xd7,
	0x06, 0x32, 0x85, 0xd8, 0xd7, 0x3d, 0xdd, 0xff, 0x17, 0xca, 0x67, 0x98, 0xfa, 0x84, 0xe3, 0xb7,
	0xb0, 0xf0, 0x07, 0xd8, 0x57, 0xe8, 0x48, 0xb0, 0xb4, 0x9f, 0x5d, 0xac, 0xa7, 0xca, 0x47, 0xf3,
	0xb9, 0xcf, 0xbd, 0xa0, 0xa3, 0xf5, 0x17, 0x83, 0xc4, 0x47, 0x76, 0xfa, 0x78, 0xc2, 0x42, 0xf3,
	0x15, 0x24, 0x8f, 0x9a, 0xb6, 0x55, 0x15, 0xaa, 0x46, 0xaa, 0x5b, 0xca, 0x32, 0x0e, 0xfe, 0x75,
	0xb2, 0xc7, 0x37, 0x30, 0xdf, 0x96, 0x65, 0x48, 0x87, 0xf6, 0x33, 0x4d, 0x37, 0x90, 0xe4, 0xda,
	0xd8, 0x93, 0x0e, 0xfb, 0x66, 0x2a, 0x5c, 0xc1, 0xf2, 0x57, 0x2b, 0x7b, 0x77, 0x8b, 0xb7, 0x99,
	0x5a, 0xf9, 0x53, 0xb8, 0xf7, 0x51, 0x77, 0xb0, 0xcd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x82,
	0xf5, 0xe0, 0x25, 0xc6, 0x01, 0x00, 0x00,
}
